package me.sma1lboy.syncchatwithdiscord.db.pojo;

public class User {
    public User() {
    }

    public User(String dcId, String dcUuid) {
        this.dcId = dcId;
        this.dcUuid = dcUuid;
    }

    public User(String dcId, String dcUuid, String mcId, String mcUuid) {
        this.dcId = dcId;
        this.dcUuid = dcUuid;
        this.mcId = mcId;
        this.mcUuid = mcUuid;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.dc_id
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    private String dcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.dc_uuid
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    private String dcUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mc_id
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    private String mcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mc_uuid
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    private String mcUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.daily_track
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    private Integer dailyTrack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_time_check
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    private String lastTimeCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.past_two_week
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    private Integer pastTwoWeek;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.dc_id
     *
     * @return the value of user.dc_id
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public String getDcId() {
        return dcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.dc_id
     *
     * @param dcId the value for user.dc_id
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void setDcId(String dcId) {
        this.dcId = dcId == null ? null : dcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.dc_uuid
     *
     * @return the value of user.dc_uuid
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public String getDcUuid() {
        return dcUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.dc_uuid
     *
     * @param dcUuid the value for user.dc_uuid
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void setDcUuid(String dcUuid) {
        this.dcUuid = dcUuid == null ? null : dcUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mc_id
     *
     * @return the value of user.mc_id
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public String getMcId() {
        return mcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mc_id
     *
     * @param mcId the value for user.mc_id
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void setMcId(String mcId) {
        this.mcId = mcId == null ? null : mcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mc_uuid
     *
     * @return the value of user.mc_uuid
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public String getMcUuid() {
        return mcUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mc_uuid
     *
     * @param mcUuid the value for user.mc_uuid
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void setMcUuid(String mcUuid) {
        this.mcUuid = mcUuid == null ? null : mcUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.daily_track
     *
     * @return the value of user.daily_track
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public Integer getDailyTrack() {
        return dailyTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.daily_track
     *
     * @param dailyTrack the value for user.daily_track
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void setDailyTrack(Integer dailyTrack) {
        this.dailyTrack = dailyTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_time_check
     *
     * @return the value of user.last_time_check
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public String getLastTimeCheck() {
        return lastTimeCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_time_check
     *
     * @param lastTimeCheck the value for user.last_time_check
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void setLastTimeCheck(String lastTimeCheck) {
        this.lastTimeCheck = lastTimeCheck == null ? null : lastTimeCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.past_two_week
     *
     * @return the value of user.past_two_week
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public Integer getPastTwoWeek() {
        return pastTwoWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.past_two_week
     *
     * @param pastTwoWeek the value for user.past_two_week
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void setPastTwoWeek(Integer pastTwoWeek) {
        this.pastTwoWeek = pastTwoWeek;
    }
}