package me.sma1lboy.syncchatwithdiscord.db.pojo;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andDcIdIsNull() {
            addCriterion("dc_id is null");
            return (Criteria) this;
        }

        public Criteria andDcIdIsNotNull() {
            addCriterion("dc_id is not null");
            return (Criteria) this;
        }

        public Criteria andDcIdEqualTo(String value) {
            addCriterion("dc_id =", value, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdNotEqualTo(String value) {
            addCriterion("dc_id <>", value, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdGreaterThan(String value) {
            addCriterion("dc_id >", value, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdGreaterThanOrEqualTo(String value) {
            addCriterion("dc_id >=", value, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdLessThan(String value) {
            addCriterion("dc_id <", value, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdLessThanOrEqualTo(String value) {
            addCriterion("dc_id <=", value, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdLike(String value) {
            addCriterion("dc_id like", value, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdNotLike(String value) {
            addCriterion("dc_id not like", value, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdIn(List<String> values) {
            addCriterion("dc_id in", values, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdNotIn(List<String> values) {
            addCriterion("dc_id not in", values, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdBetween(String value1, String value2) {
            addCriterion("dc_id between", value1, value2, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcIdNotBetween(String value1, String value2) {
            addCriterion("dc_id not between", value1, value2, "dcId");
            return (Criteria) this;
        }

        public Criteria andDcUuidIsNull() {
            addCriterion("dc_uuid is null");
            return (Criteria) this;
        }

        public Criteria andDcUuidIsNotNull() {
            addCriterion("dc_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andDcUuidEqualTo(String value) {
            addCriterion("dc_uuid =", value, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidNotEqualTo(String value) {
            addCriterion("dc_uuid <>", value, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidGreaterThan(String value) {
            addCriterion("dc_uuid >", value, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidGreaterThanOrEqualTo(String value) {
            addCriterion("dc_uuid >=", value, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidLessThan(String value) {
            addCriterion("dc_uuid <", value, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidLessThanOrEqualTo(String value) {
            addCriterion("dc_uuid <=", value, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidLike(String value) {
            addCriterion("dc_uuid like", value, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidNotLike(String value) {
            addCriterion("dc_uuid not like", value, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidIn(List<String> values) {
            addCriterion("dc_uuid in", values, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidNotIn(List<String> values) {
            addCriterion("dc_uuid not in", values, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidBetween(String value1, String value2) {
            addCriterion("dc_uuid between", value1, value2, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andDcUuidNotBetween(String value1, String value2) {
            addCriterion("dc_uuid not between", value1, value2, "dcUuid");
            return (Criteria) this;
        }

        public Criteria andMcIdIsNull() {
            addCriterion("mc_id is null");
            return (Criteria) this;
        }

        public Criteria andMcIdIsNotNull() {
            addCriterion("mc_id is not null");
            return (Criteria) this;
        }

        public Criteria andMcIdEqualTo(String value) {
            addCriterion("mc_id =", value, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdNotEqualTo(String value) {
            addCriterion("mc_id <>", value, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdGreaterThan(String value) {
            addCriterion("mc_id >", value, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdGreaterThanOrEqualTo(String value) {
            addCriterion("mc_id >=", value, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdLessThan(String value) {
            addCriterion("mc_id <", value, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdLessThanOrEqualTo(String value) {
            addCriterion("mc_id <=", value, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdLike(String value) {
            addCriterion("mc_id like", value, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdNotLike(String value) {
            addCriterion("mc_id not like", value, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdIn(List<String> values) {
            addCriterion("mc_id in", values, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdNotIn(List<String> values) {
            addCriterion("mc_id not in", values, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdBetween(String value1, String value2) {
            addCriterion("mc_id between", value1, value2, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcIdNotBetween(String value1, String value2) {
            addCriterion("mc_id not between", value1, value2, "mcId");
            return (Criteria) this;
        }

        public Criteria andMcUuidIsNull() {
            addCriterion("mc_uuid is null");
            return (Criteria) this;
        }

        public Criteria andMcUuidIsNotNull() {
            addCriterion("mc_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andMcUuidEqualTo(String value) {
            addCriterion("mc_uuid =", value, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidNotEqualTo(String value) {
            addCriterion("mc_uuid <>", value, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidGreaterThan(String value) {
            addCriterion("mc_uuid >", value, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidGreaterThanOrEqualTo(String value) {
            addCriterion("mc_uuid >=", value, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidLessThan(String value) {
            addCriterion("mc_uuid <", value, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidLessThanOrEqualTo(String value) {
            addCriterion("mc_uuid <=", value, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidLike(String value) {
            addCriterion("mc_uuid like", value, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidNotLike(String value) {
            addCriterion("mc_uuid not like", value, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidIn(List<String> values) {
            addCriterion("mc_uuid in", values, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidNotIn(List<String> values) {
            addCriterion("mc_uuid not in", values, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidBetween(String value1, String value2) {
            addCriterion("mc_uuid between", value1, value2, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andMcUuidNotBetween(String value1, String value2) {
            addCriterion("mc_uuid not between", value1, value2, "mcUuid");
            return (Criteria) this;
        }

        public Criteria andDailyTrackIsNull() {
            addCriterion("daily_track is null");
            return (Criteria) this;
        }

        public Criteria andDailyTrackIsNotNull() {
            addCriterion("daily_track is not null");
            return (Criteria) this;
        }

        public Criteria andDailyTrackEqualTo(Integer value) {
            addCriterion("daily_track =", value, "dailyTrack");
            return (Criteria) this;
        }

        public Criteria andDailyTrackNotEqualTo(Integer value) {
            addCriterion("daily_track <>", value, "dailyTrack");
            return (Criteria) this;
        }

        public Criteria andDailyTrackGreaterThan(Integer value) {
            addCriterion("daily_track >", value, "dailyTrack");
            return (Criteria) this;
        }

        public Criteria andDailyTrackGreaterThanOrEqualTo(Integer value) {
            addCriterion("daily_track >=", value, "dailyTrack");
            return (Criteria) this;
        }

        public Criteria andDailyTrackLessThan(Integer value) {
            addCriterion("daily_track <", value, "dailyTrack");
            return (Criteria) this;
        }

        public Criteria andDailyTrackLessThanOrEqualTo(Integer value) {
            addCriterion("daily_track <=", value, "dailyTrack");
            return (Criteria) this;
        }

        public Criteria andDailyTrackIn(List<Integer> values) {
            addCriterion("daily_track in", values, "dailyTrack");
            return (Criteria) this;
        }

        public Criteria andDailyTrackNotIn(List<Integer> values) {
            addCriterion("daily_track not in", values, "dailyTrack");
            return (Criteria) this;
        }

        public Criteria andDailyTrackBetween(Integer value1, Integer value2) {
            addCriterion("daily_track between", value1, value2, "dailyTrack");
            return (Criteria) this;
        }

        public Criteria andDailyTrackNotBetween(Integer value1, Integer value2) {
            addCriterion("daily_track not between", value1, value2, "dailyTrack");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckIsNull() {
            addCriterion("last_time_check is null");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckIsNotNull() {
            addCriterion("last_time_check is not null");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckEqualTo(String value) {
            addCriterion("last_time_check =", value, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckNotEqualTo(String value) {
            addCriterion("last_time_check <>", value, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckGreaterThan(String value) {
            addCriterion("last_time_check >", value, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckGreaterThanOrEqualTo(String value) {
            addCriterion("last_time_check >=", value, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckLessThan(String value) {
            addCriterion("last_time_check <", value, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckLessThanOrEqualTo(String value) {
            addCriterion("last_time_check <=", value, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckLike(String value) {
            addCriterion("last_time_check like", value, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckNotLike(String value) {
            addCriterion("last_time_check not like", value, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckIn(List<String> values) {
            addCriterion("last_time_check in", values, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckNotIn(List<String> values) {
            addCriterion("last_time_check not in", values, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckBetween(String value1, String value2) {
            addCriterion("last_time_check between", value1, value2, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andLastTimeCheckNotBetween(String value1, String value2) {
            addCriterion("last_time_check not between", value1, value2, "lastTimeCheck");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekIsNull() {
            addCriterion("past_two_week is null");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekIsNotNull() {
            addCriterion("past_two_week is not null");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekEqualTo(Integer value) {
            addCriterion("past_two_week =", value, "pastTwoWeek");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekNotEqualTo(Integer value) {
            addCriterion("past_two_week <>", value, "pastTwoWeek");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekGreaterThan(Integer value) {
            addCriterion("past_two_week >", value, "pastTwoWeek");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("past_two_week >=", value, "pastTwoWeek");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekLessThan(Integer value) {
            addCriterion("past_two_week <", value, "pastTwoWeek");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekLessThanOrEqualTo(Integer value) {
            addCriterion("past_two_week <=", value, "pastTwoWeek");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekIn(List<Integer> values) {
            addCriterion("past_two_week in", values, "pastTwoWeek");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekNotIn(List<Integer> values) {
            addCriterion("past_two_week not in", values, "pastTwoWeek");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekBetween(Integer value1, Integer value2) {
            addCriterion("past_two_week between", value1, value2, "pastTwoWeek");
            return (Criteria) this;
        }

        public Criteria andPastTwoWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("past_two_week not between", value1, value2, "pastTwoWeek");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 16 14:39:40 EST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Wed Nov 16 14:39:40 EST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}