name: SyncChatWithDiscord
version: '${project.version}'
main: me.sma1lboy.syncchatwithdiscord.SyncChatWithDiscord
api-version: 1.18
authors: [ Sma1lboy ]
description: sync the chatboard between discord and server
